/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/users": {
    /** @description Get all users */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    /** @description Create user */
    post: {
      /** @description User name */
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
  "/api/v1/users/{id}": {
    /** @description Get user by id */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": unknown;
          };
        };
        /** @description Not found */
        404: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    /** @description Delete user */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: never;
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      /**
       * Format: uuid
       * @example 54e1a86f-d786-4f9b-adb6-289cc3d9b17f
       */
      id: string;
      /** @example John Doe */
      name: string;
    };
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
